# Generated by Django 5.1.1 on 2025-07-08 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0002_post_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="post_images/"),
        ),
    ]
